### ISSUE TITLE
Clarification regarding Dataset and p1 and p2 value 

### ISSUE THREAD

**Issue by pras2020** [dhernandez0/sgm#19]
Dear All

I build sgm in jetson tx2 and executed the sample data-set the output and performance was really good but when i tried with my own dataset which was  taken from my own stereo camera the output was noisy.Can some one help me with the clarification. i am attaching the image below 

![2_4path](https://user-images.githubusercontent.com/4815599/37451490-a5e215ee-2857-11e8-9a91-db8396a63cf5.png)

cone dataset

![1](https://user-images.githubusercontent.com/4815599/37463105-381cdd5a-287a-11e8-9907-8cc8eb963f80.png)

my own dataset

![1](https://user-images.githubusercontent.com/4815599/37507060-da9837d0-2912-11e8-80fd-124aec5524cb.jpg)

![1](https://user-images.githubusercontent.com/4815599/37507065-df7dbe82-2912-11e8-8b55-ab058e5ad1c2.jpg)

**Comment by arrfou90** [comment]
Hi,
usually there performance of stereovision system is constrained due to many sources of limitations. The algorithm works pretty well although still needs after processing steps like supixel. Remember passive stereovision  is not efficient with untextured scenes (ill-posed matching problem).

**You may have a problem due to one or more of the following reasons:** 

- Your images are not clear enough (still have radiometric differences between images and blurring). Thus, you need either better image sensor or accurate calibration.  
- Asynchronized capture: a synchronized triggering of the cameras should be
done both on the hardware and the software levels, where usually left camera
is taken as reference.
-  When testing on Dataset from Middlebury there is a maximum disparity level you need to set. Some images have at least 256 disparity level which means that this implementation of SGM will not be able to find the correct correspondences (exactly as shown at the bottom part of cones disparity image).
- Adaptive P1, P2. Smoothing parameters P1 and P2 needs to be adapted according to the topology of the scene. Manual adaption usually means that you have to tune P1, P2 for different scenes (different datasets) accordingly. P2 is always > P1. 
- Settings of the stereocamers: Baseline and focal length affect the depth resolution and depth range. Smaller baseline---> accurate depth values of close objects. While, larger baseline---> accurate depth values of far objects. Considering the same focal length.

Cheers,
Arrfou
